### PR TITLE
fix: build SVT_AV1 for aarch64 or arm64

### PR DESCRIPTION
**Pull request by RaphaelVRossi**
What do you think @fdintino

### CODE REVIEW

**Comment by sadok-f** [comment]
would be great if @fdintino could review this PR.
I'm facing errors installing pillow-avif-plugin with arch arm64

**Comment by sohang3112** [comment]
Second this - @fdintino should review this PR, would be great if it makes it possible to install `piloow-avif-plugin` in ARM servers.

**Comment by jnoring-pw** [comment]
I'd also really like to see this merged--I'll be deploying to gravitron and need `arm64`. Thank you!

**Comment by fdintino** [comment]
Thanks!

**Pull request merged**
